title: "Matt Humphrey. PHP. Laravel. Git. Ruby. DevOps."
name: "PHP. Laravel. Git. Ruby. DevOps."
description: "Personal site and blog of Matt Humphrey."
url: "http://m4tt.io"
permalink: "/posts/:title.html"